#pragma config(Sensor, port3,  TouchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port4,  LineSensor,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port7,  PerpLineSensor, sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RightDrive,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         FifthWheel,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setColorMode(port4, colorTypeGrayscale_Reflected);
	int LinesCrossed = 0;
	int PreviousColor= getColorGrayscale(port7);


	while (true)
	{
		writeDebugStreamLine("%d", getColorGrayscale(port4));
		setMotorSpeed(LeftDrive,40);
		setMotorSpeed(RightDrive,40);
			if(getColorGrayscale(port4)<80)
				setMotorSpeed(FifthWheel,5);
			else if(getColorGrayscale(port4)<200)
				setMotorSpeed(FifthWheel,-10);
			if(getColorGrayscale(port7)<80)
				setTouchLEDRGB(port3, 0, 50, 0);
		else if(getColorGrayscale(port7)<200)
			setTouchLEDRGB(port3, 0, 0, 0);

		if (PreviousColor > 80 && getColorGrayscale(port7)<80)
		{
			LinesCrossed = LinesCrossed + 1;
		}
		PreviousColor = getColorGrayscale(port7);
		if (LinesCrossed == 7)
		{
			break;
		}
	}

	//resetMotorEncoder(LeftDrive);
  //resetMotorEncoder(RightDrive);
	//setMotorTarget(LeftDrive,-500,40);
	//setMotorTarget(RightDrive,-500,40);
	//waitUntilMotorStop(LeftDrive);
	//waitUntilMotorStop(RightDrive);
	//LinesCrossed = 0;
	//while (true)
	{
		//setMotorSpeed(FifthWheel,50);
		//if (PreviousColor > 80 && getColorGrayscale(port4))
		{
	//		LinesCrossed = LinesCrossed + 1;
		}
	//	PreviousColor = getColorGrayscale(port4);
	//	if (LinesCrossed == 2)
	//		break;
	}

}
