#pragma config(Motor,  motor1,          leftdrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          rightdrive,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         fifthwheel,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(leftdrive, 100);
	setMotorSpeed(rightdrive, -98.65);

sleep(6000);

	setMotorSpeed(leftdrive, -100);
	setMotorSpeed(rightdrive, 98.65);

sleep(750);

	setMotorSpeed(leftdrive, 0);
	setMotorSpeed(rightdrive, 0);
	setMotorSpeed(fifthwheel, 75);

sleep(2200);

	setMotorSpeed(fifthwheel, 0);
	setMotorSpeed(leftdrive, 100);
	setMotorSpeed(rightdrive, -98.65);

sleep(800);






}
