#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RightDrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//moves fifth wheel onto black line so it is aligned with bonus tray knocker
	setMotorSpeed(motor11, -100);
	//stops moving fifth wheel: should be aligned by now
  sleep(600);
 //turn off fifth wheel motor so robot is aligned
  setMotorSpeed (motor11, 0);
  //pauses robot, gets ready for moving back
  sleep(500);
  //Move robot backwards towards bonus tray knocker
	setMotorSpeed (motor1, -98);
	setMotorSpeed (motor6, 98);
	//Pauses motors after 7.25 seconds
	sleep(7000);
	//after bonus tray knocker has fallen, move robot forward
	setMotorSpeed (motor1, 100);
	setMotorSpeed (motor6, -100);
	//stop robot after 1 second
	sleep(1000);

	setMotorSpeed (motor1, 0);
	setMotorSpeed (motor6, 0);

	sleep(500);

	setMotorSpeed (motor11, 50);

	sleep(3000);

	setMotorSpeed (motor11, 0);

	sleep(500);

	setMotorSpeed (motor1, -100);
	setMotorSpeed (motor6, 100);

	sleep(1000);

}
