#pragma config(Sensor, port2,  ,               sensorVexIQ_Color12Color)
#pragma config(Motor,  motor5,          revolver,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setColorMode(port2, colorTypeRGB_Hue_Reflected);

		while(true) {

				//char* pColor = "***";
				int blueChannel = getColorBlueChannel(port2);
				int redChannel = getColorRedChannel(port2);
				int greenChannel = getColorGreenChannel(port2);

				writeDebugStreamLine("%3d    %3d     %3d", redChannel, greenChannel, blueChannel);

				if (blueChannel > redChannel && blueChannel > greenChannel && blueChannel > 5) {
						// blue
						setMotorTarget(motor5, 120, 100);

				} else if (redChannel > blueChannel && redChannel > greenChannel && redChannel > 5) {
						// red
						setMotorTarget(motor5, -120, 100);
				} else if (greenChannel > 5) {
						// green
						setMotorTarget(motor5, 0, 100);
				}

				waitUntilMotorStop(motor5);
		}
}
