#pragma config(Sensor, port2,  colorSensor,    sensorVexIQ_ColorHue)
#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          rightDrive,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          revolver,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         dumper,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         fifthWheel,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         conveyor,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


enum conveyorState
{
		conveyor_none = 0,
		conveyor_up = 1,
		conveyor_down = 2,
};


void setDriveMotorsState()
{
		bool isHorizontalDrive = abs(vexRT[ChC]) > 50;

		if (isHorizontalDrive == true)
		{
				if (vexRT[ChC] > 0)
				{
						motor[fifthWheel] = vexRT[ChC] - 50;
				}
				else
				{
						motor[fifthWheel] = vexRT[ChC] + 50;
				}

				motor[leftDrive] = 0;
				motor[rightDrive] = 0;
		}
		else
		{
				motor[fifthWheel] = 0;

				motor[leftDrive] = vexRT[ChA];
				motor[rightDrive] = vexRT[ChD];
		}
}

void setConveyorBeltMotorState(bool* pIsRevolverInAutoMode, conveyorState* pConveyorState)
{
		conveyorState conveyorButtonState = conveyor_none;
		if (vexRT[BtnRDown] == true)
		{
				conveyorButtonState = conveyor_down;
		}
		else if (vexRT[BtnRUp] == true)
		{
				conveyorButtonState = conveyor_up;
		}

		switch (*pConveyorState)
		{
				case conveyor_none:
						switch(conveyorButtonState)
						{
								case conveyor_down:
										*pConveyorState = conveyor_down;
										break;

								case conveyor_up:
										*pConveyorState = conveyor_up;
										break;
						}
						break;

				case conveyor_down:
						switch(conveyorButtonState)
						{
								case conveyor_down:
										*pConveyorState = conveyor_none;
										break;

								case conveyor_up:
										*pConveyorState = conveyor_up;
										break;
						}
						break;

				case conveyor_up:
						switch(conveyorButtonState)
						{
								case conveyor_down:
										*pConveyorState = conveyor_down;
										break;

								case conveyor_up:
										*pConveyorState = conveyor_none;
										break;
						}
						break;
		}

		if (*pConveyorState == conveyor_down)
		{
				*pIsRevolverInAutoMode = true;
		}
		else
		{
				*pIsRevolverInAutoMode = false;
		}

		switch (*pConveyorState)
		{
				case conveyor_none:
						motor[conveyor] = 0;
						break;

				case conveyor_down:
						motor[conveyor] = 100;
						break;

				case conveyor_up:
						motor[conveyor] = -100;
						break;
		}
}

void setRevolverMotorStateInManualMode(bool* pIsRevolverInAutoMode)
{
		int increment = 0;
		if (vexRT[BtnFUp] == true)
		{
				increment = 1;
		}
		if (vexRT[BtnFDown] == true)
		{
				increment = -1;
		}

		if (increment != 0)
		{
				*pIsRevolverInAutoMode = false;

				int stepCount = ((int)(getMotorEncoder(revolver) + 20)) / 60;
				stepCount += increment;

				setMotorTarget(revolver,  stepCount * 60, 100);
		}
		else
		{
				static int previousFineAdjustmentSpeed = 0;
				int fineAdjustmentSpeed = 0;
				if (vexRT[BtnEUp] == true)
				{
						fineAdjustmentSpeed = 15;
				}
				else if (vexRT[BtnEDown] == true)
				{
						fineAdjustmentSpeed = -15;
				}

				if (fineAdjustmentSpeed != 0)
				{
						*pIsRevolverInAutoMode = false;
						motor[revolver] = fineAdjustmentSpeed;
				}
				else if (previousFineAdjustmentSpeed != 0)
				{
						motor[revolver] = 0;
						resetMotorEncoder(revolver);
				}

				previousFineAdjustmentSpeed = fineAdjustmentSpeed;
		}
}


void setRevolverMotorStateInAutoMode()
{
		int blueChannel = getColorBlueChannel(port2);
		int redChannel = getColorRedChannel(port2);
		int greenChannel = getColorGreenChannel(port2);

		writeDebugStreamLine("%3d    %3d     %3d", redChannel, greenChannel, blueChannel);

		if (blueChannel > redChannel && blueChannel > greenChannel && blueChannel > 5)
		{
				// blue
				setMotorTarget(revolver, 120, 100);

		}
		else if (redChannel > blueChannel && redChannel > greenChannel && redChannel > 5)
		{
				// red
				setMotorTarget(revolver, -120, 100);
		}
		else if (greenChannel > 5)
		{
				// green
				setMotorTarget(revolver, 0, 100);
		}
}

void setDumperMotorState()
{
		if (vexRT[BtnLUp] == true)
		{
				motor[dumper] = 100;
		}
		else if (vexRT[BtnLDown] == true)
		{
				motor[dumper] = -100;
		}
		else
		{
				motor[dumper] = 0;
		}
}

task main()
{
		setColorMode(port2, colorTypeRGB_Hue_Reflected);
		bool isRevolverInAutoMode = false;
		conveyorState conveyorState = conveyor_none;

		while (true)
		{
			setDriveMotorsState();
			setConveyorBeltMotorState(&isRevolverInAutoMode, &conveyorState);
			setRevolverMotorStateInManualMode(&isRevolverInAutoMode);
			if (isRevolverInAutoMode == true)
			{
					setRevolverMotorStateInAutoMode();
			}
			setDumperMotorState();
		}
}
