#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          rightForkLift, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         leftForkLift,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         fifthWheel,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		while (true)
		{
				motor[leftDrive] = vexRT[ChA];
				motor[rightDrive] = vexRT[ChD];
				motor[fifthWheel] = - (vexRT[ChB] + vexRT[ChC]) / 3;

				int forkLiftValue = 0;
				if (vexRT[BtnLUp] > 0 || vexRT[BtnRUp] > 0) {
						forkLiftValue = 100;
				} else if (vexRT[BtnLDown] > 0 || vexRT[BtnRDown] > 0) {
						forkLiftValue = -100;
				}

				motor[leftForkLift] = forkLiftValue;
				motor[rightForkLift] = forkLiftValue;

				//writeDebugStreamLine("%d", vexRT[ChC]);
		}
}
