#pragma config(Sensor, port4,  LineSensor,     sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RightDrive,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         FifthWheel,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setColorMode(port4, colorTypeGrayscale_Reflected);
	while (true)
		{
		writeDebugStreamLine("%d", getColorGrayscale(port4));
		setMotorSpeed(LeftDrive,40);
		setMotorSpeed(RightDrive,40);
			if(getColorGrayscale(port4)<80)
				setMotorSpeed(FifthWheel,5);
			else if(getColorGrayscale(port4)<200)
				setMotorSpeed(FifthWheel,-10);



		}
}
