#pragma config(Motor,  motor1,           ,             tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,           ,             tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor11,          ,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setColorMode(port9, colorTypeGrayscale_Reflected);
	int threshold = 200;

	setMotorSpeed(motor1,50);
	setMotorSpeed(motor6,-50);

	while(true)
	{
		if(getColorGrayscale(port9)<threshold)
		{
	    setMotorSpeed(motor11,-20);
	  }
		else
		{
			setMotorSpeed(motor11,20);
		}
	}
}
