#pragma config(Sensor, port3,  TouchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port4,  LineSensor,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port7,  PerpLineSensor, sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LeftDrive,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RightDrive,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         FifthWheel,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setColorMode(port4, colorTypeGrayscale_Reflected);
	setColorMode(port7, colorTypeGrayscale_Reflected);
	sleep(2000);
	int LinesCrossed = 0;
	int PreviousColor= getColorGrayscale(port7);
	int lowThreshold = 60;
	int highThreshold = 160;
	int PreviousColor= highThreshold + 1;

	int greyscale = 0;
	while (true)
	{
		greyscale = getColorGrayscale(port7);
		writeDebugStreamLine("%d", getColorGrayscale(port7));
		setMotorSpeed(LeftDrive,40);
		setMotorSpeed(RightDrive,40);

		if(getColorGrayscale(port4)<100)
				setMotorSpeed(FifthWheel,5);
		else if(getColorGrayscale(port4)<200)
				setMotorSpeed(FifthWheel,-10);


		if(getColorGrayscale(port7)<lowThreshold)
			setTouchLEDRGB(port3, 0, 50, 0);
		else if(getColorGrayscale(port7)>highThreshold)
			setTouchLEDRGB(port3, 0, 0, 0);
		else
			setTouchLEDRGB(port3, 50, 0, 0);

		if(greyscale < lowThreshold || greyscale > highThreshold)
		{
			writeDebugStreamLine("color known");
			if (PreviousColor > highThreshold && greyscale < lowThreshold)
			{
				writeDebugStreamLine("Line detected!");
				LinesCrossed = LinesCrossed + 1;

				playSound(soundCarAlarm2);
				// playNote(noteA, octave3, 500);
			}

			PreviousColor = greyscale;
		}
		else
			writeDebugStreamLine("color ambiguous");

		if (LinesCrossed == 7)
		{
			break;
		}
	}
	setMotorSpeed(FifthWheel,0);
	resetMotorEncoder(LeftDrive);
	resetMotorEncoder(RightDrive);
	setMotorTarget(LeftDrive,-300,40);
	setMotorTarget(RightDrive,-300,40);
	waitUntilMotorStop(LeftDrive);
	waitUntilMotorStop(RightDrive);

	LinesCrossed = 0;

	PreviousColor = 200;
	while(true)
	{
		greyscale = getColorGrayscale(port4);
		setMotorSpeed(FifthWheel,25);
		if(getColorGrayscale(port4)<lowThreshold)
			setTouchLEDRGB(port3, 0, 50, 0);
		else if(getColorGrayscale(port4)>highThreshold)
			setTouchLEDRGB(port3, 0, 0, 0);
		else
			setTouchLEDRGB(port3, 50, 0, 0);

		if(greyscale < lowThreshold || greyscale > highThreshold)
		{
			writeDebugStreamLine("color known");
			if (PreviousColor > highThreshold && greyscale < lowThreshold)
			{
				writeDebugStreamLine("Line detected!");
				LinesCrossed = LinesCrossed + 1;

				playSound(soundCarAlarm2);
				// playNote(noteA, octave3, 500);
			}

			PreviousColor = greyscale;
		}
		if (LinesCrossed == 2)
		{
			break;
		}
	}
	resetMotorEncoder(FifthWheel);
	setMotorTarget(FifthWheel,-50,30);
	waitUntilMotorStop(FifthWheel);

	resetMotorEncoder(LeftDrive);
	resetMotorEncoder(RightDrive);
	setMotorTarget(LeftDrive,310,40);
	setMotorTarget(RightDrive,310,40);
	waitUntilMotorStop(LeftDrive);
	waitUntilMotorStop(RightDrive);
}
