#pragma config(Sensor, port8,  ColorSensor1,   sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  ColorSensor2,   sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port10, TOUCHLED,       sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  setColorMode(port8, colorTypeGrayscale_Reflected);
  setColorMode(port9, colorTypeGrayscale_Reflected);
  int CountOfLinesCrossed = 0;
  int PreviousSensorValue = getColorGrayscale(port8);

  setMotorSpeed(motor1, 100);
  setMotorSpeed(motor6, -100);

  while(true)
  {
  	int currentColor = getColorGrayscale(port8);
    if(currentColor < 100)
    {
    	// sensor reads black

    	// is the previous sensor value also black?
      if (PreviousSensorValue < 100)
      {
      	// do nothing
      }
      else
      {
     		// previous sensor value was white, so this is a transition from white to black
	    	setTouchLEDColor(port10, colorGreen);
	     	CountOfLinesCrossed = CountOfLinesCrossed + 1;
      }
    }
    else
    {
    	// sensor reads white

    	if (PreviousSensorValue < 100)
    	{
    		// this is a black to white transition, so we turn off the LED
	      setTouchLEDColor(port10, colorNone);
    	}
    	else
    	{
    		// this is a white to white transition, so we do nothing
    	}
	  }
	  PreviousSensorValue = currentColor;

	  if (CountOfLinesCrossed == 3)
	  {
	  	setMotorSpeed(motor1, 0);
	  	setMotorSpeed(motor6, 0);
	  }
	}
}
